"""Change car number datatype to ste from int PublishRide

Revision ID: 10274f1af1a9
Revises: 2fdc9cceaa23
Create Date: 2025-01-10 11:26:31.623702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10274f1af1a9'
down_revision: Union[str, None] = '2fdc9cceaa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishedrides', 'Car_Number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishedrides', 'Car_Number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
