"""Add instant booking to PublishRide

Revision ID: 1758fcbe2f0b
Revises: 
Create Date: 2025-01-09 15:09:49.435854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1758fcbe2f0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_status', sa.String(length=50), nullable=True))
    op.add_column('publishedrides', sa.Column('instant_booking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishedrides', 'instant_booking')
    op.drop_column('bookings', 'booking_status')
    # ### end Alembic commands ###
