"""add seats_remaining column to bookeide 

Revision ID: 1769e29b9e93
Revises: 1d96384dc32c
Create Date: 2025-01-13 15:57:23.404861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1769e29b9e93'
down_revision: Union[str, None] = '1d96384dc32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('seats_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'seats_remaining')
    # ### end Alembic commands ###
