"""Change booking status from enum to boolean 

Revision ID: 1d96384dc32c
Revises: 8331e95b1bcc
Create Date: 2025-01-10 12:29:17.613794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d96384dc32c'
down_revision: Union[str, None] = '8331e95b1bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_status',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
