"""remove request satus column

Revision ID: 214edd0600c6
Revises: 5275a6306a2e
Create Date: 2025-01-15 15:50:39.489138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '214edd0600c6'
down_revision: Union[str, None] = '5275a6306a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riderequests', 'message')
    op.drop_column('riderequests', 'request_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riderequests', sa.Column('request_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('riderequests', sa.Column('message', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
