"""Change car number datatype to ste from int PublishRide

Revision ID: 2fdc9cceaa23
Revises: 1758fcbe2f0b
Create Date: 2025-01-10 11:25:47.320590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdc9cceaa23'
down_revision: Union[str, None] = '1758fcbe2f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
