"""make car number column unique

Revision ID: 3e9c54311a80
Revises: 7d78a90357cc
Create Date: 2025-02-07 14:57:24.778129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9c54311a80'
down_revision: Union[str, None] = '7d78a90357cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'publishedrides', ['Car_Number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publishedrides', type_='unique')
    # ### end Alembic commands ###
