"""fix Requestride

Revision ID: 6b8e746d04f5
Revises: f546c4599b78
Create Date: 2025-01-15 14:58:36.308929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b8e746d04f5'
down_revision: Union[str, None] = 'f546c4599b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RideRequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('RideID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RideID'], ['publishedrides.id'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('riderequest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riderequest',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RideID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RideID'], ['publishedrides.id'], name='riderequest_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], name='riderequest_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('RideRequest')
    # ### end Alembic commands ###
