"""Change stopover_fare to an array

Revision ID: 6ed72474f8df
Revises: 
Create Date: 2024-12-23 14:13:58.630159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ed72474f8df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('E_mail', sa.String(length=50), nullable=True),
    sa.Column('Phone_number', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Phone_number')
    )
    op.create_index(op.f('ix_Users_E_mail'), 'Users', ['E_mail'], unique=True)
    op.create_table('Ride_Publish',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('pickup', sa.String(length=80), nullable=True),
    sa.Column('destination', sa.String(length=80), nullable=True),
    sa.Column('stopovers', mysql.JSON(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('Is_women_only', sa.Boolean(), nullable=True),
    sa.Column('Rules_', sa.String(length=1000), nullable=True),
    sa.Column('Fare', sa.String(length=50), nullable=True),
    sa.Column('StopOver_Fare', mysql.JSON(), nullable=False),
    sa.Column('Car_Number', sa.Integer(), nullable=True),
    sa.Column('Car_Type', sa.String(length=50), nullable=True),
    sa.Column('No_Of_Seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('Phone_number', table_name='users')
    op.drop_index('ix_Users_E_mail', table_name='users')
    op.drop_table('users')
    op.drop_table('publishrides_table')
    op.drop_table('ride_publish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_publish',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pickup', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('destination', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('stopovers', mysql.JSON(), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Is_women_only', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Rules_', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Fare', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('StopOver_Fare', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('Car_Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Car_Type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('No_Of_Seats', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], name='ride_publish_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('publishrides_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pickup', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('destination', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('stopovers', mysql.JSON(), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Is_women_only', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Rules_', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Fare', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('StopOver_Fare', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('Cancel_Ride', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Car_Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Car_Type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('No_Of_Seats', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], name='publishrides_table_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('E_mail', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Phone_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Users_E_mail', 'users', ['E_mail'], unique=True)
    op.create_index('Phone_number', 'users', ['Phone_number'], unique=True)
    op.drop_table('Ride_Publish')
    op.drop_index(op.f('ix_Users_E_mail'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
