"""Add isposted column

Revision ID: 7d78a90357cc
Revises: 01fa5de0c2e1
Create Date: 2025-01-29 12:35:30.465609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d78a90357cc'
down_revision: Union[str, None] = '01fa5de0c2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userextrainformation', sa.Column('isposted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userextrainformation', 'isposted')
    # ### end Alembic commands ###
